## 0.Documentation

* Чтобы более подробно ознакомиться с функцией [***read_excel***()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html), предлагаем вам обратиться к [документации]

* Чтобы более подробно ознакомиться с функцией [***to_excel()***](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html), предлагаем вам обратиться к документации.

* [openpyxl](https://openpyxl.readthedocs.io/en/stable/) — рекомендуемый пакет для чтения и записи файлов Excel 2010+ (например, xlsx); 

* [xlsxwriter](https://xlsxwriter.readthedocs.io/) — альтернативный пакет для записи данных, информации о форматировании и, в частности, диаграмм в формате Excel 2010+ (например, xlsx);

* [pyxlsb](https://pypi.org/project/pyxlsb/) — пакет позволяет читать файлы Excel в xlsb-формате;

* [pylightxl](https://pylightxl.readthedocs.io/en/latest/) — пакет позволяет читать xlsx- и xlsm-файлы и записывать xlsx-файлы;

* [xlrd](https://xlrd.readthedocs.io/en/latest/) — пакет предназначен для чтения данных и информации о форматировании из старых файлов Excel (например, xls);

* [xlwt](https://xlwt.readthedocs.io/en/latest/) — пакет предназначен для записи данных и информации о форматировании в старые файлы Excel (например, xls).

## 2. Работа с текстовыми файлами

### ИСПОЛЬЗУЕМ ФУНКЦИЮ READ_TABLE()

→ Вы уже работали с текстовыми файлами, данные в которых представлены в табличной форме. Это файлы CSV. 

Также вам известно, что, указав определенные значения параметров функции **read_csv()**, можно считать данные из файла, в котором используется разделитель данных, отличный от запятой (sep), вместо десятичной точки используется другой символ (decimal), а также при считывании должно быть пропущено некоторое количество строк (*skiprows*). 

Такие данные обычно хранятся в текстовых файлах с расширением *TXT*.   
Этот тип файлов — источник данных, который легко расшифровывать и интерпретировать. Для чтения данных из файлов такого типа Pandas, помимо функции **read_csv()**, предлагает и функцию **read_table()**.

* Функция ***read_csv()***, как вы уже знаете, загружает данные с разделителями из файла, URL-адреса, и в качестве разделителя по умолчанию используется запятая (символ).    
В документации эта функция описана как «Чтение данных из файла значений, разделённых запятыми (CSV), в DataFrame».
* Функция ***read_table()*** также загружает данные с разделителями из файла, URL-адреса, но в качестве разделителя по умолчанию используется символ табуляции ('\t').    
В документации эта функция описана как «Чтение данных из файла значений с разделителями в DataFrame».

Данные функции используются похожим образом, и то, что в настоящий момент поддерживаются они обе, обусловлено тем, что многие пользователи продолжают использовать функцию **read_table()**.    
Так, например, поиск на GitHub даёт более пятидесяти тысяч результатов по запросу *"pd.read_table"*.

Для демонстрации использования функции **read_table()** выполним следующее: 

* используя  функцию **read_csv()**, считаем данные из файла *countries.csv* в переменную countries_data, создав объект *DataFrame*;
* используя уже знакомую функцию **to_csv()**, выгрузим этот *DataFrame* в файл *countries.txt* (с расширением TXT), который сохраним в папке data. В качестве разделителя используется символ пробела (" ").


> Файл countries.csv ранее был вами сохранен в папке data. Папка создавалась при изучении материалов модуля PYTHON-10.    
Работа с различными источниками данных в Pandas. Если вы потеряли эти данные, скачайте файл [по ссылке](https://lms.skillfactory.ru/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block@DST_3.0._16_2_countries.csv) и сохраните в папке data.

In [1]:
# Импорт библиотеки pandas — при выполнении последовательно всех примеров ниже
# импорт выполняется один раз
import pandas as pd 
# Загружаем данные из файла в переменную, создавая объект DataFrame
countries_data = pd.read_csv('D:\Course_SF_DS_v3\PYTHON-10. Введение в Pandas\data/countries.csv', sep=';') 
# Выгружаем данные из DataFrame в CSV-файл и сохраняем файл в папке data
countries_data.to_csv('data/countries.txt', index=False, sep=' ')

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Course_SF_DS_v3\\PYTHON-10. Введение в Pandas\\data/countries.csv'

Считаем данные из файла countries.txt в переменную **txt_df**  (объект *DataFrame*), применив функцию ***read_table()*** с параметрами *sep=' '*  и  *index_col=['country']* (так мы избавимся от столбца с индексом и присвоим названия строкам, используя данные одного из столбцов). Выводим на экран полученный результат:

In [ ]:
# Загружаем данные из файла в переменную, создавая объект DataFrame
txt_df = pd.read_table('data/countries.txt', sep=' ', index_col=['country'])
# Выводим содержимое DataFrame на экран
display(txt_df)

           population      area
country
Англия          56.29    133396
Канада          38.05   9984670
США            322.28   9826630
Россия         146.24  17125191
Украина         45.50    603628
Беларусь         9.50    207600
Казахстан       17.04   2724902

### ПРИМЕНЕНИЕ ПАРАМЕТРА HEADER

Используя параметр ***header***, при создании DataFrame мы учитываем наличие/отсутствие строки заголовков в исходном файле данных.

Например, если при считывании данных из ранее сохранённого в папке data файла **melb_data_ps.csv** указать значение параметра **header*=None*, то первая строка исходного файла не будет восприниматься как строка заголовка и будет отнесена к области данных DataFrame:

In [ ]:
# Загружаем данные из файла в переменную, создавая объект DataFrame
melb_data = pd.read_csv('data/melb_data_ps.csv', header=None) 
# Выводим содержимое DataFrame на экран
display(melb_data)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
1,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
2,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
3,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
4,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13576,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,652.0,126.0,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,"-37.90562, 145.16761"
13577,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0,"-37.85927, 144.87904"
13578,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4.0,436.0,126.0,1997.0,NaN,-37.852740000000004,144.88738,Western Metropolitan,6380.0,"-37.85274, 144.88738"
13579,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"
13580,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,"-37.81188, 144.88449"

### РЕШАЕМ ПРОБЛЕМУ С КОДИРОВКОЙ ИСХОДНЫХ ДАННЫХ

> При считывании файла и создании DataFrame может возникнуть проблема — при выводе на экран данные будут отображаться в виде нечитаемых символов. Это связано с кодировкой символов в исходном файле.


Для решения проблемы выполним следующие действия:

* узнаем, какая кодировка символов используется в считываемом файле, для этого обратимся к субмодулю *chardet.universaldetector* библиотеки [Universal Encoding Detector](https://chardet.readthedocs.io/en/latest/usage.html). Модуль необходимо предварительно установить с помощью стандартной команды менеджера пакетов *pip: pip install chardet*;
* при считывании файла и создании DataFrame будем использовать параметр *encoding*  —  указывает, какой тип кодировки символов используется в считываемом файле. 

> ✍️ Для выполнения кода-примера скачайте файл **ErrorEnCoding.csv** по [ссылке](https://lms.skillfactory.ru/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block@ErrorEnCoding.csv) и скопируйте его в каталог data.

##### ЛОКАЛИЗУЕМ ПРОБЛЕМУ

Считываем файл и создаем DataFrame без использования параметра *encoding*:

In [ ]:
# Считываем данные из файла с неизвестной кодировкой в переменную, создавая объект DataFrame
data=pd.read_csv('data/ErrorEnCoding.csv', header=None, encoding_errors='replace') 
# Выводим содержимое DataFrame на экран
display(data)

            0                           1             2
0   User_943         Accumanst@gmail.com         ������
1   User_908           Advismowr@mail.ru         ������
2   User_962             Anachso@ukr.net      ���������
3   User_973            Antecia@inbox.ru          �����
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         ������
96  User_901          V2artierso@mail.ru    �����������
97  User_970            Vashoterlo@bk.ru        �������
98  User_965         Visuareda@yahoo.com        �������
99  User_921                Aavast@ya.ru         ������

[100 rows x 3 columns]

Выявлена проблема: при стандартном считывании содержимое файла читается некорректно. Необходимо указать кодировку файла при считывании.

##### ОПРЕДЕЛЯЕМ КОДИРОВКУ ФАЙЛА

Приведённый ниже код поможет нам определить используемую кодировку в файле, степень достоверности, используемый язык.

In [ ]:
# Импортируем субмодуль chardet.universal
from chardet.universaldetector import UniversalDetector

detector = UniversalDetector()

with open('data/ErrorEnCoding.csv', 'rb') as fh:
    for line in fh:
        detector.feed(line)
        if detector.done:
            break
print(detector.close())

{'encoding': 'KOI8-R', 'confidence': 0.8773902118791048, 'language': 'Russian'}

С достоверностью примерно 84 % тип используемой в файле кодировки — koi8-r. Повторим считывание файла, используя полученные данные.

##### СЧИТЫВАЕМ ФАЙЛ, УКАЗАВ КОДИРОВКУ

In [ ]:
# Создаем DataFrame из файла, явно указав кодировку символов, и выводим его содержимое на экран
data=pd.read_csv('data/ErrorEnCoding.csv', encoding='koi8-r', header=None)
display(data)

            0                           1             2
0   User_943         Accumanst@gmail.com         Ижевск
1   User_908           Advismowr@mail.ru         Ижевск
2   User_962             Anachso@ukr.net      Краснодар
3   User_973            Antecia@inbox.ru          Пермь
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         Тюмень
96  User_901          V2artierso@mail.ru    Арзангелтск
97  User_970            Vashoterlo@bk.ru        Воронеж
98  User_965         Visuareda@yahoo.com        Воронеж
99  User_921                Aavast@ya.ru         Ижевск

[100 rows x 3 columns]

### ЧТЕНИЕ ФАЙЛА ПО ССЫЛКЕ, ИСПОЛЬЗУЯ ФУНКЦИЮ READ_TABLE()

Ранее вы уже считывали данные из файла *melb_data.csv*, который находится в свободном доступе в интернете, используя функцию **read_csv()**.    
Попробуем использовать функцию **read_table()**, указав в качестве разделителя данных запятую — ','.

Как видим, функция read_table() сработала и с CSV-файлом — достаточно было указать, какой разделитель используется.

In [ ]:
data = pd.read_table('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv', sep=',')
display(data)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

### ЧТЕНИЕ/ЗАПИСЬ АРХИВИРОВАННЫХ CSV-ФАЙЛОВ

Механизм, используемый в функции *read_csv()*, позволяет проводить чтение текстового файла из архива, не распаковывая его.    
Функция *read_csv()* сама распознает архив и извлекает из него данные (работает практически со всеми zip-архивами).    
Есть ограничение — файл в zip-архиве должен быть один (если файлов в архиве несколько, то можно разархивировать файлы и работать с каждым вне архива.    
Подробнее об этом поговорим в юните Итоги).

Ранее вы работали с датасетом *students_performance.csv*, упакованным в архив.   
Для работы с файлом вы предварительно проводили распаковку архива. Попробуем начать работу с файлом, не распаковывая его.

✍️ Скачайте заархивированный датасет в CSV-формате *students_performance.zip* по [ссылке](https://lms.skillfactory.ru/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block@students_performance.zip)  и скопируйте его в каталог data, не распаковывая архив.

Используя функцию *read_csv()*, загрузите данные из заархивированного датасета  в переменную *data()* и выведите её содержимое на экран, используя приведённый ниже код:

In [ ]:
data = pd.read_csv('data/students_performance.zip')
display(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

В функции *to_csv()* предусмотрен механизм, позволяющий проводить упаковку CSV-файлов в zip-архив.    
Проделаем обратную операцию — данные из DataFrame data запишем в CSV-файл, упакуем полученный файл в zip-архив «на лету» и сохраним полученный архив в папке data, выполнив следующий код:

In [ ]:
# Определяем параметры архивирования — метод сжатия, имя файла в архиве
compression_opts = dict(method='zip', archive_name='out.csv') 
data.to_csv('data/out.zip', index=False, compression=compression_opts)

В ходе выполнения кода содержимое DataFrame сохранено в файле *out.csv*, файл упакован в архив *out.zip*, а архив записан в каталог *data*.

## 3. Работа с файлами Excel

### СЧИТЫВАНИЕ ДАННЫХ ИЗ ФАЙЛА EXCEL

одобно уже хорошо нам известной функции *read_csv()*, в pandas предусмотрена функция для удобного чтения **XLS**- и **XLSX**- файлов: *read_excel()* (англ. читать_Excel). Синтаксис обеих функций практически идентичен.

✍️ Для примера попробуем открыть файл *grades.xlsx*, содержащий оценки студентов за прослушанные курсы.    
[Скачайте](https://lms.skillfactory.ru/asset-v1:SkillFactory+DST-3.0+28FEB2021+type@asset+block@grades.xlsx) его и скопируйте в папку data. Для чтения файла предварительно потребуется установить библиотеку openpyxl через команду *pip install openpyxl*.

Попробуем прочитать наш файл-пример. Для этого передадим в *read_excel*() путь к нему.    
Чтобы его открыть и сохранить данные в переменную grades, необходимо выполнить следующий код:

In [3]:
grades = pd.read_excel('data/grades.xlsx')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8

> Так же, как и read_csv(), функция read_excel() может принимать на вход не только путь к файлу на компьютере, но и интернет-ссылку на него.

### СЧИТЫВАНИЕ ДАННЫХ ИЗ ФАЙЛА EXCEL ПО ССЫЛКЕ

Если файл находится в открытом доступе по ссылке (например, на Google Диске или GitHub), его можно прочитать и из интернета — для этого достаточно в функции *read_excel*() вместо пути до файла указать ссылку на файл. Например:

In [ ]:
data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx', skiprows=3)
display(data)

#### **Основные параметры метода *read_excel*()**   

* ***io*** — первый параметр, в который мы передаём адрес файла, который хотим прочитать. Кроме адреса на диске, можно передавать адрес в интернете.

* ***sheet_name*** —  ссылка на лист в Excel-файле (возможные значения данного параметра: 0 — значение по умолчанию, загружается первый лист; '*Sheet1*' — можно передать название листа; обычно листы называются '*SheetX*', где X — номер листа, но могут использоваться и другие названия; *[0, 1, 'Sheet3']* — список, содержащий номера или названия листов; в таком случае Pandas вернёт словарь, в котором ключами будут номера или названия листов, а значениями — их содержимое в виде DataFrame; None — если передать такое значение, то pandas прочитает все листы и вернёт их в виде словаря, как в предыдущем пункте).

* ***na_values*** — список значений, которые будут считаться пропусками ( ‘’, ‘#N/A’, ‘ N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’).

Следует также учесть, что нормальное поведение pandas — это считывание значений (формулы из Excel-файла не считываются).

Как упоминалось выше, один Excel-файл может включать в себя несколько листов, которые отображаются в разных вкладках (англ. sheet, рус. лист). Например, в нашем файле два листа — *Maths* и *ML*.

По умолчанию в DataFrame читается информация из первого листа, однако *read_excel*()  позволяет выбрать, из какого именно листа загружать данные.    
Сделать это можно с помощью параметра sheet_name (рус. имя_листа). Например, чтобы прочесть данные из второго листа (ML) файла, выполним код:

In [5]:
grades = pd.read_excel('data/grades.xlsx', sheet_name='ML')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9

### ВЫГРУЗКА ДАННЫХ ИЗ DATAFRAME В EXCEL-ФАЙЛ

После обработки данных (очистка, создание новых признаков и т. д.) методами и функциями pandas мы сталкиваемся с обратной задачей — сохранить данные из DataFrame в Excel-файл.

Для этого в pandas есть функция ***to_excel***() (рус. в_Excel), принцип работы которой очень схож с функцией **to_csv**():

In [6]:
# Сохраняем данные из DataFrame grades в файл grades_new.xlsx в папке data
grades.to_excel('data/grades_new.xlsx')

В этом случае будет создан один лист с именем по умолчанию "*Sheet1*". Также мы сохраним и индекс — в данных будет находиться лишний столбец.    
Чтобы создать лист с определённым именем (например, *Example*) и не сохранять индекс, в метод  *to_excel*() необходимо передать параметры:   

 ***sheet_name***='Example'     
 ***index***=False:

### Задание 3.3

Для выполнения следующего задания вам потребуется файл *ratings+movies.xlsx*, содержащий два листа с данными: *ratings* (таблица с информацией о выставленных оценках) и *movies* (таблица c расшифровками идентификаторов кинофильмов).   
[Скачайте](https://lms-cdn.skillfactory.ru/assets/courseware/v1/d56d7f6eded3ab0872fd91a06c970f68/asset-v1:SkillFactory+DSPR-2.0+14JULY2021+type@asset+block/ratings_movies.xlsx) его и посмотрите, как он выглядит.


Считайте данные из двух листов файла ratings+movies.xlsx в разные DataFrame, объедините в один, запишите данные из полученного DataFrame в файл. Сколько строк (включая строку заголовков) в результирующем файле?

In [8]:
# Читаем файл на каждом листе
ratings_df = pd.read_excel('data/ratings_movies.xlsx', sheet_name='ratings')
movies_df = pd.read_excel('data/ratings_movies.xlsx', sheet_name='movies')

# Объединяем оба датафрейма в один
ratmov_df = ratings_df.merge(
    movies_df,
    on='movieId',
    how='left'
)    
ratmov_df.to_excel('data/ratmov_df.xlsx')